// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRwWx_4oGKtqzFNkLZh8xoPl8opwbJMvg',
    appId: '1:144277401934:web:0eb55586785cb5625f2e1f',
    messagingSenderId: '144277401934',
    projectId: 'hot-summer-9a82c',
    authDomain: 'hot-summer-9a82c.firebaseapp.com',
    storageBucket: 'hot-summer-9a82c.appspot.com',
    measurementId: 'G-84CLMJWPVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3jftW-3Nf49AhxWbDUCSIBgYb1JHbXLw',
    appId: '1:144277401934:android:0aa58cde21ff9fe05f2e1f',
    messagingSenderId: '144277401934',
    projectId: 'hot-summer-9a82c',
    storageBucket: 'hot-summer-9a82c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosU66Tl17wYYMvLZNbhPUlHNbMbru_MA',
    appId: '1:144277401934:ios:a47f452e5e8854715f2e1f',
    messagingSenderId: '144277401934',
    projectId: 'hot-summer-9a82c',
    storageBucket: 'hot-summer-9a82c.appspot.com',
    androidClientId: '144277401934-bdbp4telshi4rrvg7o6o7ue6sgok54nc.apps.googleusercontent.com',
    iosClientId: '144277401934-lcr6bdkmd8p6uvkrecrvrvmki996af1u.apps.googleusercontent.com',
    iosBundleId: 'com.ethannetz.hotsummer',
  );
}
