version: "3.8"
name: hotsummer
services:
  app:
    image: ethernetz/docker-flutter:latest
    container_name: flutter
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    privileged: true
    command: /bin/sh -c "while sleep 1000; do :; done"

  firebase:
    build:
      context: ./firebase
    container_name: firebase   
    ports:
      - 4000:4000 # Used for emulator UI
      - 8080:8080 # Used for firestore emulator
      - 9099:9099 # Used for auth emulator
      - 5001:5001 # Used for functions emulator
      - 9005:9005 # Used for `firebase login` authentication 
    volumes:
      - ./firebase:/home/node/app
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command:
      # Copy node_modules into volume-mounted directory so we can see them in dev environment
      [
        sh,
        -c,
        "cp -r /home/node/functions-cache/. /home/node/app/functions/. && firebase --project=hot-summer-9a82c emulators:start --only auth,firestore,functions --import=./emulator-cache --export-on-exit & npm run build:watch --prefix ./functions"
      ]
