version: "3.8"
name: hotsummer
services:
  app:
    image: flutter
    build:
      context: ./app
    ports:
      - 6080:6080 # Used Android emulator UI
    volumes:
      - .:/workspace:cached # Mount the root folder that contains .git
    privileged: true
    command: /bin/sh -c "while sleep 1000; do :; done"

  firebase:
    image: firebase
    build:
      context: ./firebase
    ports:
      - 4000:4000 # Used for emulator UI
      - 8080:8080 # Used for firestore emulator
      - 9099:9099 # Used for auth emulator
      - 5001:5001 # Used for functions emulator
      - 9005:9005 # Used for `firebase login` authentication 
    volumes:
      - ./firebase:/home/node/app
      - .:/workspace:cached # Mount the root folder that contains .git
    command: /bin/sh -c "while sleep 1000; do :; done"