enum ActivityMeasurementType {
  reps("Reps"),
  pounds("lbs"),
  assistedPounds("-lbs"),
  additionalPounds("+lbs"),
  time("Time"),
  miles("Miles");

  const ActivityMeasurementType(this.displayName);
  final String displayName;
}

enum ActivityType {
  airSquat(1, 'Air Squat',
      [ActivityMeasurementType.pounds, ActivityMeasurementType.reps]),
  backExtension(2, 'Back Extension',
      [ActivityMeasurementType.additionalPounds, ActivityMeasurementType.reps]),
  // bandPullApart(5, 'Band Pull-Apart'),
  // bandedSideKicks(6, 'Banded Side Kicks'),
  // barDip(7, 'Bar Dip'),
  // barHang(8, 'Bar Hang'),
  // barbellCurl(9, 'Barbell Curl'),
  // barbellFrontRaise(10, 'Barbell Front Raise'),
  // barbellHackSquat(11, 'Barbell Hack Squat'),
  // barbellLunge(12, 'Barbell Lunge'),
  // barbellLyingTricepsExtension(13, 'Barbell Lying Triceps Extension'),
  // barbellPreacherCurl(14, 'Barbell Preacher Curl'),
  // barbellRearDeltRow(15, 'Barbell Rear Delt Row'),
  // barbellRow(16, 'Barbell Row'),
  // barbellShrug(17, 'Barbell Shrug'),
  // barbellStandingTricepsExtension(18, 'Barbell Standing Triceps Extension'),
  // barbellUprightRow(19, 'Barbell Upright Row'),
  // barbellWalkingLunge(20, 'Barbell Walking Lunge'),
  // barbellWristCurl(21, 'Barbell Wrist Curl'),
  // barbellWristCurlBehindTheBack(22, 'Barbell Wrist Curl Behind the Back'),
  // barbellWristExtension(23, 'Barbell Wrist Extension'),
  // behindTheNeckPress(24, 'Behind the Neck Press'),
  // beltSquat(25, 'Belt Squat'),
  // benchDip(26, 'Bench Dip'),
  // benchPress(27, 'Bench Press'),
  // blockSnatch(28, 'Block Snatch'),
  // bodyWeightLunge(29, 'Body Weight Lunge'),
  // bodyweightCurl(30, 'Bodyweight Curl'),
  // boxSquat(31, 'Box Squat'),
  // bulgarianSplitSquat(32, 'Bulgarian Split Squat'),
  // cableChestPress(33, 'Cable Chest Press'),
  // cableCloseGripSeatedRow(34, 'Cable Close Grip Seated Row'),
  // cableCrunch(35, 'Cable Crunch'),
  // cableCurlWithBar(36, 'Cable Curl With Bar'),
  // cableCurlWithRope(37, 'Cable Curl With Rope'),
  // cableLateralRaise(38, 'Cable Lateral Raise'),
  // cablePullThrough(39, 'Cable Pull Through'),
  // cableRearDeltRow(40, 'Cable Rear Delt Row'),
  // cableWideGripSeatedRow(41, 'Cable Wide Grip Seated Row'),
  // chairSquat(42, 'Chair Squat'),
  // chinUp(43, 'Chin-Up'),
  // clamshells(44, 'Clamshells'),
  // clean(45, 'Clean'),
  // cleanAndJerk(46, 'Clean and Jerk'),
  // closeGripBenchPress(47, 'Close-Grip Bench Press'),
  // closeGripFeetUpBenchPress(48, 'Close-Grip Feet-Up Bench Press'),
  // closeGripPushUp(49, 'Close-Grip Push-Up'),
  // concentrationCurl(50, 'Concentration Curl'),
  // crunch(51, 'Crunch'),
  // deadBug(52, 'Dead Bug'),
  // deadlift(53, 'Deadlift'),
  // declineBenchPress(54, 'Decline Bench Press'),
  // deficitDeadlift(55, 'Deficit Deadlift'),
  // dumbbellChestFly(56, 'Dumbbell Chest Fly'),
  // dumbbellChestPress(57, 'Dumbbell Chest Press'),
  // dumbbellCurl(58, 'Dumbbell Curl'),
  // dumbbellDeadlift(59, 'Dumbbell Deadlift'),
  // dumbbellDeclineChestPress(60, 'Dumbbell Decline Chest Press'),
  // dumbbellFloorPress(61, 'Dumbbell Floor Press'),
  // dumbbellFrogPumps(62, 'Dumbbell Frog Pumps'),
  // dumbbellFrontRaise(63, 'Dumbbell Front Raise'),
  // dumbbellHorizontalExternalShoulderRotation(
  //     64, 'Dumbbell Horizontal External Shoulder Rotation'),
  // dumbbellHorizontalInternalShoulderRotation(
  //     65, 'Dumbbell Horizontal Internal Shoulder Rotation'),
  // dumbbellLateralRaise(66, 'Dumbbell Lateral Raise'),
  // dumbbellLunge(67, 'Dumbbell Lunge'),
  // dumbbellLyingTricepsExtension(68, 'Dumbbell Lying Triceps Extension'),
  // dumbbellPreacherCurl(69, 'Dumbbell Preacher Curl'),
  // dumbbellPullover(70, 'Dumbbell Pullover'),
  // dumbbellRearDeltRow(71, 'Dumbbell Rear Delt Row'),
  // dumbbellRomanianDeadlift(72, 'Dumbbell Romanian Deadlift'),
  // dumbbellRow(73, 'Dumbbell Row'),
  // dumbbellShoulderPress(74, 'Dumbbell Shoulder Press'),
  // dumbbellShrug(75, 'Dumbbell Shrug'),
  // dumbbellSquat(76, 'Dumbbell Squat'),
  // dumbbellStandingTricepsExtension(77, 'Dumbbell Standing Triceps Extension'),
  // dumbbellWristCurl(78, 'Dumbbell Wrist Curl'),
  // dumbbellWristExtension(79, 'Dumbbell Wrist Extension'),
  // eccentricHeelDrop(80, 'Eccentric Heel Drop'),
  // facePull(81, 'Face Pull'),
  // farmersWalk(82, 'Farmers Walk'),
  // fatBarDeadlift(83, 'Fat Bar Deadlift'),
  // feetUpBenchPress(84, 'Feet-Up Bench Press'),
  // fireHydrants(85, 'Fire Hydrants'),
  // floorBackExtension(86, 'Floor Back Extension'),
  // floorPress(87, 'Floor Press'),
  // frogPumps(88, 'Frog Pumps'),
  // frontHold(89, 'Front Hold'),
  // frontSquat(90, 'Front Squat'),
  // gluteBridge(91, 'Glute Bridge'),
  // gobletSquat(92, 'Goblet Squat'),
  // goodMorning(93, 'Good Morning'),
  // gripper(94, 'Gripper'),
  // hackSquatMachine(95, 'Hack Squat Machine'),
  // halfAirSquat(96, 'Half Air Squat'),
  // hammerCurl(97, 'Hammer Curl'),
  // hangClean(98, 'Hang Clean'),
  // hangPowerClean(99, 'Hang Power Clean'),
  // hangPowerSnatch(100, 'Hang Power Snatch'),
  // hangSnatch(101, 'Hang Snatch'),
  // hangingKneeRaise(102, 'Hanging Knee Raise'),
  // hangingLegRaise(103, 'Hanging Leg Raise'),
  // hangingSitUp(104, 'Hanging Sit-Up'),
  // heelRaise(105, 'Heel Raise'),
  // highToLowWoodChopWithBand(106, 'High to Low Wood Chop with Band'),
  // hipAbductionAgainstBand(107, 'Hip Abduction Against Band'),
  // hipAbductionMachine(108, 'Hip Abduction Machine'),
  // hipAdductionMachine(109, 'Hip Adduction Machine'),
  // hipThrust(110, 'Hip Thrust'),
  // hipThrustMachine(111, 'Hip Thrust Machine'),
  // hipThrustWithBandAroundKnees(112, 'Hip Thrust With Band Around Knees'),
  // horizontalWoodChopWithBand(113, 'Horizontal Wood Chop with Band'),
  // inclineBenchPress(114, 'Incline Bench Press'),
  // inclineDumbbellCurl(115, 'Incline Dumbbell Curl'),
  // inclineDumbbellPress(116, 'Incline Dumbbell Press'),
  // inclinePushUp(117, 'Incline Push-Up'),
  // invertedRow(118, 'Inverted Row'),
  // invertedRowWithUnderhandGrip(119, 'Inverted Row with Underhand Grip'),
  // kettlebellSwing(120, 'Kettlebell Swing'),
  // kneelingAbWheelRollOut(121, 'Kneeling Ab Wheel Roll-Out'),
  // kneelingInclinePushUp(122, 'Kneeling Incline Push-Up'),
  // kneelingPlank(123, 'Kneeling Plank'),
  // kneelingPushUp(124, 'Kneeling Push-Up'),
  // kneelingSidePlank(125, 'Kneeling Side Plank'),
  // landmineHackSquat(126, 'Landmine Hack Squat'),
  // landmineSquat(127, 'Landmine Squat'),
  // latPulldownWithPronatedGrip(128, 'Lat Pulldown With Pronated Grip'),
  // latPulldownWithSupinatedGrip(129, 'Lat Pulldown With Supinated Grip'),
  // lateralWalkWithBand(130, 'Lateral Walk With Band'),
  // legExtension(131, 'Leg Extension'),
  // legPress(132, 'Leg Press'),
  // lyingDumbbellExternalShoulderRotation(
  //     133, 'Lying Dumbbell External Shoulder Rotation'),
  // lyingDumbbellInternalShoulderRotation(
  //     134, 'Lying Dumbbell Internal Shoulder Rotation'),
  // lyingLegCurl(135, 'Lying Leg Curl'),
  // lyingLegRaise(136, 'Lying Leg Raise'),
  // lyingWindshieldWiper(137, 'Lying Windshield Wiper'),
  // lyingWindshieldWiperWithBentKnees(
  //     138, 'Lying Windshield Wiper with Bent Knees'),
  // machineBicepCurl(139, 'Machine Bicep Curl'),
  // machineChestFly(140, 'Machine Chest Fly'),
  // machineChestPress(141, 'Machine Chest Press'),
  // machineCrunch(142, 'Machine Crunch'),
  // machineGluteKickbacks(143, 'Machine Glute Kickbacks'),
  // machineLateralRaise(144, 'Machine Lateral Raise'),
  // machineShoulderPress(145, 'Machine Shoulder Press'),
  // monkeyRow(146, 'Monkey Row'),
  // mountainClimbers(147, 'Mountain Climbers'),
  // obliqueCrunch(148, 'Oblique Crunch'),
  // obliqueSitUp(149, 'Oblique Sit-Up'),
  // oneHandedBarHang(150, 'One-Handed Bar Hang'),
  // oneHandedCableRow(151, 'One-Handed Cable Row'),
  // oneHandedLatPulldown(152, 'One-Handed Lat Pulldown'),
  // oneLeggedGluteBridge(153, 'One-Legged Glute Bridge'),
  // oneLeggedHipThrust(154, 'One-Legged Hip Thrust'),
  // overheadCableTricepsExtension(155, 'Overhead Cable Triceps Extension'),
  // overheadPress(156, 'Overhead Press'),
  // pauseDeadlift(157, 'Pause Deadlift'),
  // pauseSquat(158, 'Pause Squat'),
  // pecDeck(159, 'Pec Deck'),
  // pendlayRow(160, 'Pendlay Row'),
  // plank(161, 'Plank'),
  // plateFrontRaise(162, 'Plate Front Raise'),
  // platePinch(163, 'Plate Pinch'),
  // plateWristCurl(164, 'Plate Wrist Curl'),
  // powerClean(165, 'Power Clean'),
  // powerJerk(166, 'Power Jerk'),
  // powerSnatch(167, 'Power Snatch'),
  // pullUp(168, 'Pull-Up'),
  // pushPress(169, 'Push Press'),
  // pushUp(170, 'Push-Up'),
  // pushUpAgainstWall(171, 'Push-Up Against Wall'),
  // pushUpsWithFeetInRings(172, 'Push-Ups With Feet in Rings'),
  // rackPull(173, 'Rack Pull'),
  // resistanceBandChestFly(174, 'Resistance Band Chest Fly'),
  // reverseDumbbellFlyes(175, 'Reverse Dumbbell Flyes'),
  // reverseMachineFly(176, 'Reverse Machine Fly'),
  // romanianDeadlift(177, 'Romanian Deadlift'),
  // safetyBarSquat(178, 'Safety Bar Squat'),
  // sealRow(179, 'Seal Row'),
  // seatedBarbellOverheadPress(180, 'Seated Barbell Overhead Press'),
  // seatedCalfRaise(181, 'Seated Calf Raise'),
  // seatedDumbbellShoulderPress(182, 'Seated Dumbbell Shoulder Press'),
  // seatedLegCurl(183, 'Seated Leg Curl'),
  // seatedMachineRow(184, 'Seated Machine Row'),
  // seatedSmithMachineShoulderPress(185, 'Seated Smith Machine Shoulder Press'),
  // shallowBodyWeightLunge(186, 'Shallow Body Weight Lunge'),
  // sideLungesBodyweight(187, 'Side Lunges (Bodyweight)'),
  // sidePlank(188, 'Side Plank'),
  // singleLegRomanianDeadlift(189, 'Single Leg Romanian Deadlift'),
  // sitUp(190, 'Sit-Up'),
  // smithMachineBenchPress(191, 'Smith Machine Bench Press'),
  // smithMachineInclineBenchPress(192, 'Smith Machine Incline Bench Press'),
  // smithMachineSquat(193, 'Smith Machine Squat'),
  // snatch(194, 'Snatch'),
  // snatchGripBehindTheNeckPress(195, 'Snatch Grip Behind the Neck Press'),
  // snatchGripDeadlift(196, 'Snatch Grip Deadlift'),
  // spiderCurl(197, 'Spider Curl'),
  // splitJerk(198, 'Split Jerk'),
  // squat(199, 'Squat'),
  // squatJerk(200, 'Squat Jerk'),
  // standingCableChestFly(201, 'Standing Cable Chest Fly'),
  // standingCalfRaise(202, 'Standing Calf Raise'),
  // standingGluteKickbackInMachine(203, 'Standing Glute Kickback in Machine'),
  // standingResistanceBandChestFly(204, 'Standing Resistance Band Chest Fly'),
  // stepUp(205, 'Step Up'),
  // stiffLeggedDeadlift(206, 'Stiff-Legged Deadlift'),
  // straightArmLatPulldown(207, 'Straight Arm Lat Pulldown'),
  // sumoDeadlift(208, 'Sumo Deadlift'),
  // tBarRow(209, 'T-Bar Row'),
  // towelPullUp(210, 'Towel Pull-Up'),
  // trapBarDeadliftWithHighHandles(211, 'Trap Bar Deadlift With High Handles'),
  // trapBarDeadliftWithLowHandles(212, 'Trap Bar Deadlift With Low Handles'),
  // tricepBodyweightExtension(213, 'Tricep Bodyweight Extension'),
  // tricepPushdownWithBar(214, 'Tricep Pushdown With Bar'),
  tricepPushdownWithRope(215, 'Tricep Pushdown With Rope',
      [ActivityMeasurementType.pounds, ActivityMeasurementType.reps]);

  static final Map<int, ActivityType> _map = {
    for (var value in ActivityType.values) value.number: value
  };

  static ActivityType fromNumber(int number) => _map[number]!;

  const ActivityType(this.number, this.displayName, this.measurementTypes);

  final int number;
  final String displayName;
  final List<ActivityMeasurementType> measurementTypes;
}
