name: iOS binary build & upload

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - app/**

jobs:
  deploy:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Set up flutter env
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.1'
        channel: 'stable'
        architecture: x64

    - run: flutter pub get
      working-directory: ./app
    - run: flutter build ios --release --no-codesign
      working-directory: ./app

    - name: Decode signing certificate into a file
      env:
        CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
      run: |
        echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12
      working-directory: ./app/ios

    - name: Deploy to TestFlight via Fastlane
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: build_upload_testflight
        subdirectory: app/ios
      env:
        ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
        DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
        SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        SIGNING_KEY_FILE_PATH: signing-cert.p12
