name: Deploy to firebase
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - firebase/**

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore,functions -f --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./firebase
